language: python

before_install:
  - if [${TRAVIS_OS_NAME} == "linux"]; then sudo apt-get update -qq; fi
  - sh src/install-dependencies.sh

matrix:
  include:
    - name: "Linux, 3.7, pip"
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
      python: 3.7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libblas-dev', 'liblapack-dev', 'libopenblas-dev']

script:
  - cd src
  - make CXX=$CXX
  - cd ../
  - which python
  - pip install --upgrade -e .
  - pip install coverage pytest pytest-cov
  - pytest --pyargs robustpca --cov=robustpca robustpca/

notifications:
  email: false
