# Travis file

language: generic

before_install:
  - if [${TRAVIS_OS_NAME} == "linux"]; then sudo apt-get update -qq; fi
  - sh src/install-dependencies.sh

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
      python: 3.7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libblas-dev', 'liblapack-dev', 'libopenblas-dev']

script:
  - cd src
  - make CXX=$CXX
  - cd ../
  - pip install --upgrade -e .
  - pytest--pyargs robustpca --cov=robustpca robustpca/"

notifications:
  email: false
