language: python

env:
  global:
    - DEPS="numba"
    - TEST_DEPS="pytest pytest-cov coveralls"

matrix:
  include:
  - env: export PYTHON=3.7
  - env: export PYTHON=3.6
  - env: export PYTHON=3.7
    os: osx
    language: generic

sudo: True

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      curl "https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" -o miniconda.sh;
    else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh;
    ./miniconda.sh -b -p $HOME/miniconda;
    hash -r;
  - source $HOME/miniconda/bin/activate root;
    conda update -y conda;
    conda config --append channels conda-forge;
    conda create -n testenv --yes python=$PYTHON;
    source activate testenv;
  - conda info -a
  - df -h

install:
  - conda install -y $DEPS $TEST_DEPS $DOC_DEPS;
  - pip install .

script:
  - pytest --pyargs robustpca --cov=robustpca

after_success:
  - coveralls
